#################
# Site settings #
#################

url: http://food.kevincrimi.com
baseurl: ""

title: FoodBlog
email: kevincrimi@gmail.com
description: "Taking you down to Chinatown, one bite at a time"

google-tracking-id: "UA-71210506-3"

